#!/bin/sh

export PATH=/usr/local/lib/python2.7/dist-packages/cassspectr/ui:/usr/local/bin/:$PATH

#/usr/local/lib/python2.7/dist-packages/cassspectr/ui/newcontrol.py
#cd
/usr/local/bin/newcontrol.py > ~/uistartup.log
