# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Nov 16 14:23:04 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1736, 846)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.profileGraph = QtGui.QGraphicsView(self.centralWidget)
        self.profileGraph.setGeometry(QtCore.QRect(1430, 20, 291, 221))
        self.profileGraph.setObjectName(_fromUtf8("profileGraph"))
        self.spec1DView = QtGui.QGraphicsView(self.centralWidget)
        self.spec1DView.setGeometry(QtCore.QRect(330, 290, 1061, 381))
        self.spec1DView.setObjectName(_fromUtf8("spec1DView"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(1520, 250, 131, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(350, 30, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(350, 300, 91, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.extractWinSlider = QtGui.QSlider(self.centralWidget)
        self.extractWinSlider.setEnabled(False)
        self.extractWinSlider.setGeometry(QtCore.QRect(1500, 310, 160, 23))
        self.extractWinSlider.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.extractWinSlider.setAcceptDrops(False)
        self.extractWinSlider.setAutoFillBackground(False)
        self.extractWinSlider.setTracking(True)
        self.extractWinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.extractWinSlider.setInvertedAppearance(False)
        self.extractWinSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.extractWinSlider.setTickInterval(10)
        self.extractWinSlider.setObjectName(_fromUtf8("extractWinSlider"))
        self.SB1Slider = QtGui.QSlider(self.centralWidget)
        self.SB1Slider.setGeometry(QtCore.QRect(1440, 360, 81, 23))
        self.SB1Slider.setOrientation(QtCore.Qt.Horizontal)
        self.SB1Slider.setObjectName(_fromUtf8("SB1Slider"))
        self.SB2Slider = QtGui.QSlider(self.centralWidget)
        self.SB2Slider.setGeometry(QtCore.QRect(1610, 360, 81, 23))
        self.SB2Slider.setOrientation(QtCore.Qt.Horizontal)
        self.SB2Slider.setObjectName(_fromUtf8("SB2Slider"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(1530, 330, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(1450, 380, 111, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(1610, 380, 111, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButAutoExtract = QtGui.QPushButton(self.centralWidget)
        self.pushButAutoExtract.setGeometry(QtCore.QRect(1520, 270, 131, 24))
        self.pushButAutoExtract.setObjectName(_fromUtf8("pushButAutoExtract"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(57, 421, 57, 15))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pushButCurrFrame = QtGui.QPushButton(self.centralWidget)
        self.pushButCurrFrame.setGeometry(QtCore.QRect(1590, 470, 99, 24))
        self.pushButCurrFrame.setObjectName(_fromUtf8("pushButCurrFrame"))
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(1450, 450, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEditCurrFrame = QtGui.QLineEdit(self.centralWidget)
        self.lineEditCurrFrame.setEnabled(True)
        self.lineEditCurrFrame.setGeometry(QtCore.QRect(1450, 470, 131, 23))
        self.lineEditCurrFrame.setObjectName(_fromUtf8("lineEditCurrFrame"))
        self.pushButCurrArc = QtGui.QPushButton(self.centralWidget)
        self.pushButCurrArc.setGeometry(QtCore.QRect(1590, 520, 99, 24))
        self.pushButCurrArc.setObjectName(_fromUtf8("pushButCurrArc"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(1450, 500, 101, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEditCurrArc = QtGui.QLineEdit(self.centralWidget)
        self.lineEditCurrArc.setEnabled(True)
        self.lineEditCurrArc.setGeometry(QtCore.QRect(1450, 520, 131, 23))
        self.lineEditCurrArc.setObjectName(_fromUtf8("lineEditCurrArc"))
        self.curFlatBut = QtGui.QPushButton(self.centralWidget)
        self.curFlatBut.setEnabled(False)
        self.curFlatBut.setGeometry(QtCore.QRect(1590, 570, 99, 24))
        self.curFlatBut.setObjectName(_fromUtf8("curFlatBut"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(1450, 550, 101, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.currFlatFill = QtGui.QLineEdit(self.centralWidget)
        self.currFlatFill.setEnabled(False)
        self.currFlatFill.setGeometry(QtCore.QRect(1450, 570, 131, 23))
        self.currFlatFill.setObjectName(_fromUtf8("currFlatFill"))
        self.curFluxCalBut = QtGui.QPushButton(self.centralWidget)
        self.curFluxCalBut.setEnabled(False)
        self.curFluxCalBut.setGeometry(QtCore.QRect(1590, 620, 99, 24))
        self.curFluxCalBut.setObjectName(_fromUtf8("curFluxCalBut"))
        self.label_12 = QtGui.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(1450, 600, 101, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.currFluxCalFill = QtGui.QLineEdit(self.centralWidget)
        self.currFluxCalFill.setEnabled(False)
        self.currFluxCalFill.setGeometry(QtCore.QRect(1450, 620, 131, 23))
        self.currFluxCalFill.setObjectName(_fromUtf8("currFluxCalFill"))
        self.lineEditz0 = QtGui.QLineEdit(self.centralWidget)
        self.lineEditz0.setGeometry(QtCore.QRect(50, 40, 113, 23))
        self.lineEditz0.setObjectName(_fromUtf8("lineEditz0"))
        self.lineEditz1 = QtGui.QLineEdit(self.centralWidget)
        self.lineEditz1.setGeometry(QtCore.QRect(200, 40, 113, 23))
        self.lineEditz1.setObjectName(_fromUtf8("lineEditz1"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 21, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(180, 40, 21, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.comboBoxScaling = QtGui.QComboBox(self.centralWidget)
        self.comboBoxScaling.setGeometry(QtCore.QRect(70, 70, 78, 24))
        self.comboBoxScaling.setObjectName(_fromUtf8("comboBoxScaling"))
        self.comboBoxScaling.addItem(_fromUtf8(""))
        self.comboBoxScaling.addItem(_fromUtf8(""))
        self.comboBoxScaling.addItem(_fromUtf8(""))
        self.zScaleUpdateBut = QtGui.QPushButton(self.centralWidget)
        self.zScaleUpdateBut.setGeometry(QtCore.QRect(190, 70, 99, 24))
        self.zScaleUpdateBut.setObjectName(_fromUtf8("zScaleUpdateBut"))
        self.useSB1Check = QtGui.QCheckBox(self.centralWidget)
        self.useSB1Check.setGeometry(QtCore.QRect(1450, 400, 85, 21))
        self.useSB1Check.setChecked(True)
        self.useSB1Check.setObjectName(_fromUtf8("useSB1Check"))
        self.useSB2Check = QtGui.QCheckBox(self.centralWidget)
        self.useSB2Check.setGeometry(QtCore.QRect(1620, 400, 85, 21))
        self.useSB2Check.setChecked(True)
        self.useSB2Check.setObjectName(_fromUtf8("useSB2Check"))
        self.raw2DGraph = QtGui.QGraphicsView(self.centralWidget)
        self.raw2DGraph.setGeometry(QtCore.QRect(330, 20, 1061, 221))
        self.raw2DGraph.setObjectName(_fromUtf8("raw2DGraph"))
        self.checkBoxShowSB = QtGui.QCheckBox(self.centralWidget)
        self.checkBoxShowSB.setGeometry(QtCore.QRect(90, 120, 141, 21))
        self.checkBoxShowSB.setChecked(True)
        self.checkBoxShowSB.setObjectName(_fromUtf8("checkBoxShowSB"))
        self.checkBoxShowExtractWin = QtGui.QCheckBox(self.centralWidget)
        self.checkBoxShowExtractWin.setGeometry(QtCore.QRect(90, 150, 191, 21))
        self.checkBoxShowExtractWin.setChecked(True)
        self.checkBoxShowExtractWin.setObjectName(_fromUtf8("checkBoxShowExtractWin"))
        self.logView = QtGui.QTextEdit(self.centralWidget)
        self.logView.setGeometry(QtCore.QRect(30, 440, 281, 231))
        self.logView.setObjectName(_fromUtf8("logView"))
        self.pushButPan = QtGui.QPushButton(self.centralWidget)
        self.pushButPan.setGeometry(QtCore.QRect(1140, 260, 80, 23))
        self.pushButPan.setObjectName(_fromUtf8("pushButPan"))
        self.pushButZoom = QtGui.QPushButton(self.centralWidget)
        self.pushButZoom.setGeometry(QtCore.QRect(1220, 260, 80, 23))
        self.pushButZoom.setObjectName(_fromUtf8("pushButZoom"))
        self.pushButResetView = QtGui.QPushButton(self.centralWidget)
        self.pushButResetView.setGeometry(QtCore.QRect(1300, 260, 80, 23))
        self.pushButResetView.setObjectName(_fromUtf8("pushButResetView"))
        self.checkBoxLockDisplays = QtGui.QCheckBox(self.centralWidget)
        self.checkBoxLockDisplays.setGeometry(QtCore.QRect(1000, 260, 121, 21))
        self.checkBoxLockDisplays.setObjectName(_fromUtf8("checkBoxLockDisplays"))
        self.pushButSmoothObj = QtGui.QPushButton(self.centralWidget)
        self.pushButSmoothObj.setGeometry(QtCore.QRect(970, 680, 121, 23))
        self.pushButSmoothObj.setObjectName(_fromUtf8("pushButSmoothObj"))
        self.spinBoxSmoothWidth = QtGui.QSpinBox(self.centralWidget)
        self.spinBoxSmoothWidth.setGeometry(QtCore.QRect(1100, 680, 47, 24))
        self.spinBoxSmoothWidth.setMaximum(20)
        self.spinBoxSmoothWidth.setProperty("value", 0)
        self.spinBoxSmoothWidth.setObjectName(_fromUtf8("spinBoxSmoothWidth"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(1160, 690, 57, 15))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButNoSmooth = QtGui.QPushButton(self.centralWidget)
        self.pushButNoSmooth.setGeometry(QtCore.QRect(1230, 680, 121, 23))
        self.pushButNoSmooth.setObjectName(_fromUtf8("pushButNoSmooth"))
        self.comboBoxColorMap = QtGui.QComboBox(self.centralWidget)
        self.comboBoxColorMap.setGeometry(QtCore.QRect(208, 210, 111, 31))
        self.comboBoxColorMap.setObjectName(_fromUtf8("comboBoxColorMap"))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.comboBoxColorMap.addItem(_fromUtf8(""))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(120, 210, 101, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.checkBoxWrite1Dascii = QtGui.QCheckBox(self.centralWidget)
        self.checkBoxWrite1Dascii.setGeometry(QtCore.QRect(40, 360, 171, 21))
        self.checkBoxWrite1Dascii.setChecked(True)
        self.checkBoxWrite1Dascii.setObjectName(_fromUtf8("checkBoxWrite1Dascii"))
        self.checkBoxWrite1DFITS = QtGui.QCheckBox(self.centralWidget)
        self.checkBoxWrite1DFITS.setGeometry(QtCore.QRect(40, 380, 171, 21))
        self.checkBoxWrite1DFITS.setChecked(True)
        self.checkBoxWrite1DFITS.setObjectName(_fromUtf8("checkBoxWrite1DFITS"))
        self.lineEditDataDir = QtGui.QLineEdit(self.centralWidget)
        self.lineEditDataDir.setEnabled(False)
        self.lineEditDataDir.setGeometry(QtCore.QRect(30, 270, 211, 23))
        self.lineEditDataDir.setText(_fromUtf8(""))
        self.lineEditDataDir.setObjectName(_fromUtf8("lineEditDataDir"))
        self.lineEditOutDataDir = QtGui.QLineEdit(self.centralWidget)
        self.lineEditOutDataDir.setEnabled(False)
        self.lineEditOutDataDir.setGeometry(QtCore.QRect(30, 320, 211, 23))
        self.lineEditOutDataDir.setText(_fromUtf8(""))
        self.lineEditOutDataDir.setObjectName(_fromUtf8("lineEditOutDataDir"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(30, 250, 101, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.centralWidget)
        self.label_18.setGeometry(QtCore.QRect(30, 300, 101, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.pushButChooseDataDir = QtGui.QPushButton(self.centralWidget)
        self.pushButChooseDataDir.setGeometry(QtCore.QRect(250, 270, 61, 23))
        self.pushButChooseDataDir.setObjectName(_fromUtf8("pushButChooseDataDir"))
        self.pushButChooseOutDataDir = QtGui.QPushButton(self.centralWidget)
        self.pushButChooseOutDataDir.setGeometry(QtCore.QRect(250, 320, 61, 23))
        self.pushButChooseOutDataDir.setObjectName(_fromUtf8("pushButChooseOutDataDir"))
        self.pushButCurrFrameBrowse = QtGui.QPushButton(self.centralWidget)
        self.pushButCurrFrameBrowse.setGeometry(QtCore.QRect(1590, 440, 99, 24))
        self.pushButCurrFrameBrowse.setObjectName(_fromUtf8("pushButCurrFrameBrowse"))
        self.pushButIgnoreWLC = QtGui.QPushButton(self.centralWidget)
        self.pushButIgnoreWLC.setGeometry(QtCore.QRect(350, 680, 91, 23))
        self.pushButIgnoreWLC.setObjectName(_fromUtf8("pushButIgnoreWLC"))
        self.label_15 = QtGui.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(400, 260, 561, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEditExpType = QtGui.QLineEdit(self.centralWidget)
        self.lineEditExpType.setEnabled(True)
        self.lineEditExpType.setGeometry(QtCore.QRect(520, 680, 81, 22))
        self.lineEditExpType.setReadOnly(True)
        self.lineEditExpType.setObjectName(_fromUtf8("lineEditExpType"))
        self.lineEditGrating = QtGui.QLineEdit(self.centralWidget)
        self.lineEditGrating.setEnabled(True)
        self.lineEditGrating.setGeometry(QtCore.QRect(610, 680, 81, 22))
        self.lineEditGrating.setReadOnly(True)
        self.lineEditGrating.setObjectName(_fromUtf8("lineEditGrating"))
        self.lineEditGratingAngle = QtGui.QLineEdit(self.centralWidget)
        self.lineEditGratingAngle.setEnabled(True)
        self.lineEditGratingAngle.setGeometry(QtCore.QRect(700, 680, 81, 22))
        self.lineEditGratingAngle.setReadOnly(True)
        self.lineEditGratingAngle.setObjectName(_fromUtf8("lineEditGratingAngle"))
        self.lineEditArcLamp = QtGui.QLineEdit(self.centralWidget)
        self.lineEditArcLamp.setEnabled(True)
        self.lineEditArcLamp.setGeometry(QtCore.QRect(790, 680, 81, 22))
        self.lineEditArcLamp.setReadOnly(True)
        self.lineEditArcLamp.setObjectName(_fromUtf8("lineEditArcLamp"))
        self.label_19 = QtGui.QLabel(self.centralWidget)
        self.label_19.setGeometry(QtCore.QRect(530, 700, 71, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.centralWidget)
        self.label_20.setGeometry(QtCore.QRect(620, 700, 61, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.centralWidget)
        self.label_21.setGeometry(QtCore.QRect(710, 700, 71, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.centralWidget)
        self.label_22.setGeometry(QtCore.QRect(800, 700, 71, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pushButIgnoreWLClibArc = QtGui.QPushButton(self.centralWidget)
        self.pushButIgnoreWLClibArc.setGeometry(QtCore.QRect(350, 710, 151, 23))
        self.pushButIgnoreWLClibArc.setObjectName(_fromUtf8("pushButIgnoreWLClibArc"))
        self.comboBoxExtractionType = QtGui.QComboBox(self.centralWidget)
        self.comboBoxExtractionType.setGeometry(QtCore.QRect(1440, 690, 251, 31))
        self.comboBoxExtractionType.setObjectName(_fromUtf8("comboBoxExtractionType"))
        self.comboBoxExtractionType.addItem(_fromUtf8(""))
        self.comboBoxExtractionType.addItem(_fromUtf8(""))
        self.comboBoxExtractionType.addItem(_fromUtf8(""))
        self.comboBoxExtractionType.addItem(_fromUtf8(""))
        self.label_23 = QtGui.QLabel(self.centralWidget)
        self.label_23.setGeometry(QtCore.QRect(1440, 670, 151, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1736, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionSet_data_dir = QtGui.QAction(MainWindow)
        self.actionSet_data_dir.setObjectName(_fromUtf8("actionSet_data_dir"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionMedian_counts_per_pixel = QtGui.QAction(MainWindow)
        self.actionMedian_counts_per_pixel.setObjectName(_fromUtf8("actionMedian_counts_per_pixel"))
        self.actionMedian_counts_in_extraction_window_x_Npix = QtGui.QAction(MainWindow)
        self.actionMedian_counts_in_extraction_window_x_Npix.setObjectName(_fromUtf8("actionMedian_counts_in_extraction_window_x_Npix"))
        self.actionSummed_counts_over_extraction_window = QtGui.QAction(MainWindow)
        self.actionSummed_counts_over_extraction_window.setObjectName(_fromUtf8("actionSummed_counts_over_extraction_window"))
        self.actionPeak_row_in_extraction_window = QtGui.QAction(MainWindow)
        self.actionPeak_row_in_extraction_window.setObjectName(_fromUtf8("actionPeak_row_in_extraction_window"))
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.zScaleUpdateBut, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.update)
        QtCore.QObject.connect(self.checkBoxShowExtractWin, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.show)
        QtCore.QObject.connect(self.SB1Slider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), MainWindow.show)
        QtCore.QObject.connect(self.useSB1Check, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.raise_)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Spatial profile (pix)", None))
        self.label_2.setText(_translate("MainWindow", "Raw 2D spectrum", None))
        self.label_4.setText(_translate("MainWindow", "1D spectrum", None))
        self.label_5.setText(_translate("MainWindow", "Extraction window", None))
        self.label_6.setText(_translate("MainWindow", "Side band 1", None))
        self.label_7.setText(_translate("MainWindow", "Side band 2", None))
        self.pushButAutoExtract.setText(_translate("MainWindow", "Auto determine", None))
        self.label_8.setText(_translate("MainWindow", "Log", None))
        self.pushButCurrFrame.setText(_translate("MainWindow", "Update", None))
        self.label_9.setText(_translate("MainWindow", "Current Frame", None))
        self.pushButCurrArc.setText(_translate("MainWindow", "Update", None))
        self.label_10.setText(_translate("MainWindow", "Arc used", None))
        self.curFlatBut.setText(_translate("MainWindow", "Update", None))
        self.label_11.setText(_translate("MainWindow", "Flat used", None))
        self.curFluxCalBut.setText(_translate("MainWindow", "Update", None))
        self.label_12.setText(_translate("MainWindow", "Fluxcal used", None))
        self.label_13.setText(_translate("MainWindow", "z0", None))
        self.label_14.setText(_translate("MainWindow", "z1", None))
        self.comboBoxScaling.setItemText(0, _translate("MainWindow", "ZScale", None))
        self.comboBoxScaling.setItemText(1, _translate("MainWindow", "Manual", None))
        self.comboBoxScaling.setItemText(2, _translate("MainWindow", "Min/Max", None))
        self.zScaleUpdateBut.setText(_translate("MainWindow", "Update", None))
        self.useSB1Check.setText(_translate("MainWindow", "Use", None))
        self.useSB2Check.setText(_translate("MainWindow", "Use", None))
        self.checkBoxShowSB.setText(_translate("MainWindow", "Display side bands", None))
        self.checkBoxShowExtractWin.setText(_translate("MainWindow", "Display extraction window", None))
        self.pushButPan.setText(_translate("MainWindow", "Pan", None))
        self.pushButZoom.setText(_translate("MainWindow", "Zoom", None))
        self.pushButResetView.setText(_translate("MainWindow", "Reset View", None))
        self.checkBoxLockDisplays.setText(_translate("MainWindow", "Lock Displays", None))
        self.pushButSmoothObj.setText(_translate("MainWindow", "Smooth object", None))
        self.label_3.setText(_translate("MainWindow", "pixels", None))
        self.pushButNoSmooth.setText(_translate("MainWindow", "No smoothing", None))
        self.comboBoxColorMap.setItemText(0, _translate("MainWindow", "gist_gray", None))
        self.comboBoxColorMap.setItemText(1, _translate("MainWindow", "gist_gray_r", None))
        self.comboBoxColorMap.setItemText(2, _translate("MainWindow", "gist_rainbow", None))
        self.comboBoxColorMap.setItemText(3, _translate("MainWindow", "gist_rainbow_r", None))
        self.comboBoxColorMap.setItemText(4, _translate("MainWindow", "Blues", None))
        self.comboBoxColorMap.setItemText(5, _translate("MainWindow", "Blues_r", None))
        self.comboBoxColorMap.setItemText(6, _translate("MainWindow", "cool", None))
        self.comboBoxColorMap.setItemText(7, _translate("MainWindow", "cool_r", None))
        self.label_16.setText(_translate("MainWindow", "Colour map", None))
        self.checkBoxWrite1Dascii.setText(_translate("MainWindow", "Auto-write 1D ascii", None))
        self.checkBoxWrite1DFITS.setText(_translate("MainWindow", "Auto-write 1D FITS", None))
        self.label_17.setText(_translate("MainWindow", "Input data dir", None))
        self.label_18.setText(_translate("MainWindow", "Output data dir", None))
        self.pushButChooseDataDir.setText(_translate("MainWindow", "Choose", None))
        self.pushButChooseOutDataDir.setText(_translate("MainWindow", "Choose", None))
        self.pushButCurrFrameBrowse.setText(_translate("MainWindow", "Browse", None))
        self.pushButIgnoreWLC.setText(_translate("MainWindow", "ignore WLC", None))
        self.label_15.setText(_translate("MainWindow", "Note: images/plots flipped in x so that wavelength runs blue-->red, as God intended", None))
        self.label_19.setText(_translate("MainWindow", "EXPTYPE", None))
        self.label_20.setText(_translate("MainWindow", "GRATING", None))
        self.label_21.setText(_translate("MainWindow", "GR-ANGLE", None))
        self.label_22.setText(_translate("MainWindow", "ARC-LAMP", None))
        self.pushButIgnoreWLClibArc.setText(_translate("MainWindow", "use nearest library arc", None))
        self.comboBoxExtractionType.setItemText(0, _translate("MainWindow", "Peak row in extraction window", None))
        self.comboBoxExtractionType.setItemText(1, _translate("MainWindow", "Summed counts over extraction window", None))
        self.comboBoxExtractionType.setItemText(2, _translate("MainWindow", "Median counts in extraction window x window width", None))
        self.comboBoxExtractionType.setItemText(3, _translate("MainWindow", "Median counts per pixel in extraction window", None))
        self.label_23.setText(_translate("MainWindow", "Extraction type", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSet_data_dir.setText(_translate("MainWindow", "Set data dir", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionMedian_counts_per_pixel.setText(_translate("MainWindow", "Median counts per pixel", None))
        self.actionMedian_counts_in_extraction_window_x_Npix.setText(_translate("MainWindow", "Median counts in extraction window x Npix", None))
        self.actionSummed_counts_over_extraction_window.setText(_translate("MainWindow", "Summed counts within extraction window", None))
        self.actionPeak_row_in_extraction_window.setText(_translate("MainWindow", "Peak row in extraction window", None))

